spring:
  application:
    name: hr-api-gateway

  redis:
    port: 6379
    host: localhost

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

